////

|metadata|
{
    "name": "documentengine-report-graphics",
    "controlName": ["Infragistics Document Engine"],
    "tags": [],
    "guid": "{0FCBC065-1184-45B1-B61C-02A33454A938}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Report Graphics



Report graphics give omph to your reports through several graphical elements such as Brushes, Colors, Fonts, and Images. Use report graphics to augment layout elements. For example, use a brush and pen to color the background and borders of an element, respectively. You can also add color and modify fonts on link:documentengine-pattern-content.html[pattern content] such as Tables, Lists, and Text. Any layout or content element can by affected by report graphics in some way or another.

Click the links below to learn more about report graphics.

* link:documentengine-brushes.html[Brushes]
* link:documentengine-canvas.html[Canvas]
* link:documentengine-colors.html[Colors]
* link:documentengine-fonts.html[Fonts]
* link:documentengine-pens.html[Pens]
* link:documentengine-shapes.html[Shapes]