////

|metadata|
{
    "name": "documentengine-quick-image",
    "controlName": ["Infragistics Document Engine"],
    "tags": [],
    "guid": "{2FE53039-F852-4F0B-8A77-DCD1E9B52BE3}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Quick Image



The Quick Image element lets you add images to most layout elements with little or no effort. To quickly add an image to your report, you simply need to call the AddQuickImage method of whichever layout element you need to insert an image in. This method has only one parameter, an  pick:[win-forms=" link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.graphics.image.html[Infragistics.Documents.Reports.Graphics.Image]"]   pick:[asp-net=" link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.graphics.image.html[Infragistics.Documents.Reports.Graphics.Image]"]   pick:[win-forms-old=" link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.graphics.image.html[Infragistics.Documents.Reports.Graphics.Image]"]   pick:[aspnet-old=" link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.graphics.image.html[Infragistics.Documents.Reports.Graphics.Image]"]  . You can either pass in a previously created image, or you can instantiate a new image. See Image for more information.

The following code creates a Quick Image element by calling the  pick:[win-forms=" link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection~addquickimage.html[AddQuickImage]"]   pick:[asp-net=" link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection~addquickimage.html[AddQuickImage]"]   pick:[win-forms-old=" link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection~addquickimage.html[AddQuickImage]"]   pick:[aspnet-old=" link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection~addquickimage.html[AddQuickImage]"]  method off the  pick:[win-forms=" link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection]"]   pick:[asp-net=" link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection]"]   pick:[win-forms-old=" link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection]"]   pick:[aspnet-old=" link:{ApiPlatform}webui.documents.reports{ApiVersion}~infragistics.documents.reports.report.section.isection.html[ISection]"]  interface and passing in a new image. The new image will use the second overload, using a string to identify the path of the image. This topic assumes that you have a Report element defined with at least one Section element added to it. See link:documentengine-report.html[Report] and link:documentengine-section.html[Section] for more information.

*In Visual Basic:*

----
section1.AddQuickImage(New Image(Application.StartupPath + "..\Coffee Bean.bmp"))
----

*In C#:*

----
section1.AddQuickImage(new Image(Application.StartupPath + @"..\Coffee Bean.bmp"));
----