////

|metadata|
{
    "name": "documentengine-report-layout",
    "controlName": ["Infragistics Document Engine"],
    "tags": [],
    "guid": "{E3A1B042-5224-4967-9CC5-BBE9434A2558}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Report Layout



Report layout elements make it easier for you to add content. Each element has specific functions and features that make it unique. You can use the link:documentengine-layout-element-comparison-table.html[Layout Element Comparison Table] to figure out which layout element will fit your needs best.

Click the links below to learn more about each layout element.

* link:documentengine-layout-element-comparison-table.html[Layout Element Comparison Table]
* link:documentengine-advanced-layout-elements.html[Advanced Layout Elements]
* link:documentengine-container-and-condition.html[Container and Condition]
* link:documentengine-band.html[Band]
* link:documentengine-flow.html[Flow]
* link:documentengine-group.html[Group]
* link:documentengine-page-break.html[Page Break]
* link:documentengine-report.html[Report]
* link:documentengine-section.html[Section]
* link:documentengine-segment.html[Segment]